Added the ShareCard screen
siddeshpillai/jetpack-compose-playground pull request #15
Opened 2022-10-03 19:19 UTC by Abishek1997

ref #13 

- Added the ShareCard screen which contains data, composables and Components 
- Exposes and uses the ShareCardCustom() and ShareCardDefault() reusable composable UI functions
- Material3 theme styled components are added
- Added GlideImage composable to load images and drawables
- Further requirements are handled in drawables, component's gradle, Manifest file to setup the ShareCard
- Comments are added throughout the file explaining the usage of each composable/ function

2022-10-03 23:16 UTC, siddeshpillai commented on app/src/main/java/com/compose/playground/MainActivity.kt
> +        composable("Share Card"){
@Abishek1997 missing space `){`

2022-10-03 23:17 UTC, siddeshpillai commented on components/build.gradle
> +    implementation "com.google.accompanist:accompanist-drawablepainter:0.26.4-beta" // drawablePainter
@Abishek1997 Why do you need this?

2022-10-03 23:18 UTC, siddeshpillai commented on components/src/main/res/drawable/ic_baseline_more_horiz_24.xml
> +    android:tint="#000000" android:viewportHeight="24"
@Abishek1997 Can you use the vector provided by the SDK?

2022-10-03 23:18 UTC, siddeshpillai commented on components/src/main/res/drawable/ic_baseline_share_24.xml
> +    android:viewportWidth="24" android:width="24dp" xmlns:android="http://schemas.android.com/apk/res/android">
@Abishek1997 Can you use the vector provided by the SDK?

2022-10-03 23:18 UTC, siddeshpillai requested changes
@Abishek1997 Some minor comments to resolve.

2022-10-03 23:19 UTC, siddeshpillai commented on components/src/main/java/com/compose/components/ShareCard.kt
> +fun ShareScreenScaffold(
`()` can be in one line since there are no args

2022-10-04 00:13 UTC, Abishek1997 commented
Made the above mentioned changes.

2022-10-04 18:54 UTC, siddeshpillai requested changes
If possible rely primary and onPrimary colors. 
Image is not circular for icon
text and background of the shade card needs to designed for both light and dark theme
![image](https://user-images.githubusercontent.com/4101783/193901969-51ce6034-cce4-46cc-b483-084d23b3d364.png)

Switching theme caused results in image loading issues 
![image](https://user-images.githubusercontent.com/4101783/193902383-37d97a02-5884-4d67-93a6-1e2afcc5d21b.png)

2022-10-14 19:06 UTC, Abishek1997 commented
Made changes to use Material3 surface, primary, onSurface, onPrimary variants for all UI based elements. Replaced the screenshots in the original comment

2022-10-14 23:07 UTC, siddeshpillai approved these changes

2022-10-14 23:08 UTC, merged